###############################################################################
## master
###############################################################################
-
  branches:
    only:
      - master
  skip_tags: true
  image: Ubuntu2004
  version: 1.0.{build}
  environment:
    GIT_TERMINAL_PROMPT: 0
    NODEJS_VERSION: 18.16.0
  init:
    - nvm install $NODEJS_VERSION
    - nvm use $NODEJS_VERSION
  install:
    - npm install
    - npm install -g gulp
  build_script:
    - gulp scripts
  after_build:
    - chmod +x ./publish
    - ./publish
  notifications:
  - provider: Email
    to:
    - a.linca@moodmedia.com
    - l.domsa@moodmedia.com
    subject: '[Appveyor] {{projectName}}/{{branch}}/{{buildVersion}} {{status}}'
    message: >-
      <div style="font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;">
          {{#passed}}
              <h1 style="font-size: 150%;font-weight:normal; color:#078DC7;">
                  <a href="{{buildUrl}}" style="color:#078DC7;">Build {{projectName}}/{{branch}}/{{buildVersion}} completed</a>
              </h1>
          {{/passed}}
          {{#failed}}
              <h1 style="font-size: 150%;font-weight:normal; color:#ff3228;">
                  <a href="{{buildUrl}}" style="color:#ff3228;">Build {{projectName}}/{{branch}}/{{buildVersion}} failed</a>
              </h1>
          {{/failed}}
          <p style="color: #888;">
              Commit <a href="{{commitUrl}}">{{commitId}}</a> by <a href="mailto:{{commitAuthorEmail}}">{{commitAuthor}}</a> on {{commitDate}}:
              <br />
              <span style="font-size: 110%;color:#222;">{{commitMessage}}</span>
          </p>
          <p><a href="{{notificationSettingsUrl}}" style="font-size:85%;color:#999;">Configure your notification preferences</a></p>
      </div>
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
